### ISSUE TITLE
automate.sh fails

### ISSUE THREAD

**Issue by dimthe** [styxlab/kubernetes-mongodb-shard#5]
hello , i get this error can you help ? i am running this on CentOS atomic hosts

src/automate.sh
01: Initialize replication set rs01 on node 01
Execute command on pod mongodb-shard-node01-1268161559-xdv4z and container rsp01-node01
Unable to use a TTY - input is not a terminal or the right kind of file
error: Internal error occurred: error executing command in container: container not found ("rsp01-node01")
make: *** [run] Error 1
[root@atomic01 kubernetes-mongodb-shard]#

**Comment by dimthe** [comment]
i think i need to add in your yaml files in /build this parameter :  tty: true
if this is true , where do i enter this ?

**Comment by styxlab** [comment]
The `tty` message is just a warning and can be ignored. The real error is `container not found ("rsp01-node01")`. So either, something failed during the create phase (see `src/create.sh`) or you have slow cluster and you need to increase the `sleep 60` to something larger in the `Makefile`. What does the following command give you?
```
kubectl get po/mongodb-shard-node01-1268161559-xdv4z
```

**Comment by dimthe** [comment]
hello @styxlab 

i deleted everything and started over.
the first part finishes with no errors

Successfully executed.
Execute 'make run' to fire up the mongodb shard on your cluster.
[root@atomic01 kubernetes-mongodb-shard]# 


make run failed 
01: Initialize replication set rs01 on node 01
Execute command on pod mongodb-shard-node01-456883099-7vdrl and container rsp01-node01
Unable to use a TTY - input is not a terminal or the right kind of file
error: Internal error occurred: error executing command in container: container not found ("rsp01-node01")
make: *** [run] Error 1
[root@atomic01 kubernetes-mongodb-shard]# 

and

[root@atomic01 kubernetes-mongodb-shard]# kubectl get po/mongodb-shard-node01-456883099-7vdrl
NAME                                   READY     STATUS             RESTARTS   AGE
mongodb-shard-node01-456883099-7vdrl   1/5       CrashLoopBackOff   16         2m
[root@atomic01 kubernetes-mongodb-shard]# 



please advise :)

**Comment by dimthe** [comment]
same error with sleep 120

sleep 120
src/automate.sh
01: Initialize replication set rs01 on node 01
Execute command on pod mongodb-shard-node01-456883099-7bqc3 and container rsp01-node01
Unable to use a TTY - input is not a terminal or the right kind of file
error: Internal error occurred: error executing command in container: container not found ("rsp01-node01")
make: *** [run] Error 1

 kubectl get po/mongodb-shard-node01-456883099-7bqc3 
NAME                                   READY     STATUS             RESTARTS   AGE
mongodb-shard-node01-456883099-7bqc3   1/5       CrashLoopBackOff   16         3m

**Comment by dimthe** [comment]
same error with sleep 300 

full log output 


[root@atomic01 kubernetes-mongodb-shard]# make build
src/clean.sh
src/generate.sh

Please supply some important configuration parameters below:
============================================================
SSH user for cluster access [root]: 
SSH port for cluster access [22]: 
Root directory for your mongodb data [/data]: /var
Number of nodes for your shard [5]: 
MongoDB version [3.2]: 

Please ensure that pods can be scheduled on all these nodes.
------------------------------------------------------------
CLUSTER NODES.....................: 5
SHARD MEMBERS.....................: 5
MONGOS PER CLUSTER................: 5
CONFIG SERVERS PER CLUSTER........: 1
CONFIG REPLICAS PER CLUSTER.......: 5
DATA REPLICAS PER SHARD...........: 2
ARBITER PER REPLICA SET...........: 1
TOTAL REPLICAS PER SHARD..........: 3
------------------------------------------------------------
SHARDED CLUSTER DATA REDUNDANCY...: 2
DISK SPACE FACTOR ................: 2.5 (times GB per node)
------------------------------------------------------------
Generate Kubernetes YAML files according to spec...
rsp01-node01-port27020
rss02-node01-port27021
arb03-node01-port27019
---
rss01-node02-port27021
arb02-node02-port27019
rsp05-node02-port27020
---
arb01-node03-port27019
rsp04-node03-port27020
rss05-node03-port27021
---
rsp03-node04-port27020
rss04-node04-port27021
arb05-node04-port27019
---
rsp02-node05-port27020
rss03-node05-port27021
arb04-node05-port27019
---
Config Server replicas loop...
cfg01-node01-port27018
cfg01-node02-port27018
cfg01-node03-port27018
cfg01-node04-port27018
cfg01-node05-port27018
---
Mongos server loop...
mgs01-node01-port27017
mgs01-node02-port27017
mgs01-node03-port27017
mgs01-node04-port27017
mgs01-node05-port27017
Generate needed directories on remote server ...
Number of Shards / Replication Sets: 5
Executing commands on atomic02...
Ensure correct kernel settings for mongodb...
Create directories for replica set 01.
Create directories for replica set 02.
Create directories for replica set 03.
Create directories for replica set 04.
Create directories for replica set 05.
Executing commands on atomic03...
Ensure correct kernel settings for mongodb...
Create directories for replica set 01.
Create directories for replica set 02.
Create directories for replica set 03.
Create directories for replica set 04.
Create directories for replica set 05.
Executing commands on atomic04...
Ensure correct kernel settings for mongodb...
Create directories for replica set 01.
Create directories for replica set 02.
Create directories for replica set 03.
Create directories for replica set 04.
Create directories for replica set 05.
Executing commands on atomic05...
Ensure correct kernel settings for mongodb...
Create directories for replica set 01.
Create directories for replica set 02.
Create directories for replica set 03.
Create directories for replica set 04.
Create directories for replica set 05.
Executing commands on atomic06...
Ensure correct kernel settings for mongodb...
Create directories for replica set 01.
Create directories for replica set 02.
Create directories for replica set 03.
Create directories for replica set 04.
Create directories for replica set 05.

Successfully executed.
Execute 'make run' to fire up the mongodb shard on your cluster.
[root@atomic01 kubernetes-mongodb-shard]# make run
src/create.sh
Create Deployment on machine atomic02 (node01)...
service "mongodb-node01" created
deployment "mongodb-shard-node01" created
Create Deployment on machine atomic03 (node02)...
service "mongodb-node02" created
deployment "mongodb-shard-node02" created
Create Deployment on machine atomic04 (node03)...
service "mongodb-node03" created
deployment "mongodb-shard-node03" created
Create Deployment on machine atomic05 (node04)...
service "mongodb-node04" created
deployment "mongodb-shard-node04" created
Create Deployment on machine atomic06 (node05)...
service "mongodb-node05" created
deployment "mongodb-shard-node05" created
sleep 300
src/automate.sh
01: Initialize replication set rs01 on node 01
Execute command on pod mongodb-shard-node01-456883099-bmswr and container rsp01-node01
Unable to use a TTY - input is not a terminal or the right kind of file
error: Internal error occurred: error executing command in container: container not found ("rsp01-node01")
make: *** [run] Error 1
[root@atomic01 kubernetes-mongodb-shard]# 
kubectl get po/mongodb-shard-node01-456883099-bmswr 
NAME                                   READY     STATUS             RESTARTS   AGE
mongodb-shard-node01-456883099-bmswr   1/5       CrashLoopBackOff   24         8m

**Comment by dimthe** [comment]
been trying to get this to work all day @styxlab  , can't  figure out whats wrong with it . any tips?

**Comment by styxlab** [comment]
You need to figure out why the create step fails. The important line from the above logs is `mongodb-shard-node01-456883099-bmswr 1/5 CrashLoopBackOff 24 8m`. This means, only 1 of the 5 pods started correctly, the other are stuck in a crash loop. Does the following command: 
```
kubectl describe po/mongodb-shard-node01-456883099-bmswr
```
give you a better hint? Also, try to start out small, with 3 nodes and build up step by step.

**Comment by styxlab** [comment]
Closed due to inactivity. Please reopen, if problem persist.
