### ISSUE TITLE
How to expose mongos externally?

### ISSUE THREAD

**Issue by y2kbowen** [styxlab/kubernetes-mongodb-shard#9]
I followed along and have everything running. Under the consume section of the readme it shows the lines for the exposed services but the only address it shows is the cluster-ip.  The external-ip shows none. Is there something in the configuration that maps the mongos server to an external IP?  I ask because when I try to connect to the listed servers from robomongo for example, I cannot connect using the cluster ip address or the address of the node.

**Comment by styxlab** [comment]
You need an ingress or an external load balancer to connect to your shard from the outside. This repo only exposes the shard to inside the kubernetes cluster. This is not different form any other deployment of your kubernetes cluster that you want to access externally.

Within the kubernetes cluster you can connect directly to the shard through the service endpoints provided.
